<?php require './templates/header.phtml' ?>

<ul class="list-group list-group-item-info">
<?php foreach($directores as $director): ?>
    <li class="list-group-item list-group-item-action list-group-item-info">
        <div>
            <b><?= $director->id ?></b> | <?=$director->nombre?>
            <button><a href="formDirectores/<?=$director->id?>">Editar</a></button>
            <button><a href="directores/<?=$director->id?>">Ver</a></button>
        </div>
        
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> directores</small></p>


<?php require './templates/footer.phtml' ?>