<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action='formDirectores<?php if (isset($id)) {echo "/" . $id; } ?>'>
        <input type="text" name="nombre" placeholder="Director">
        <?php if (isset($id)) { ?>
            <button type="submit" class="btn btn-primary mt-3">Modificar director</button>
        <?php
        } else { ?>
            <button type="submit" class="btn btn-primary mt-3">Agregar director</button>
        <?php } ?>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>